### ISSUE TITLE
Refatorar as Rotas do Backend

### ISSUE THREAD

**Issue by uira** [EscolaDeSaudePublica/gestao-ventiladores-backend#49]
Estrtura básica das rotas
![Untitled Diagram (1)](https://user-images.githubusercontent.com/6399202/82500745-62360480-9aca-11ea-93c1-e2c87b83882e.jpg)

**Comment by oxechicao** [comment]
Resultado da reunião de hoje foi esse diagrama padronizando as rotas e as respostas.
![Untitled Diagram (1)](https://user-images.githubusercontent.com/6399202/82500745-62360480-9aca-11ea-93c1-e2c87b83882e.jpg)

Em ordem de prioridade
- [x] Documentar no Swagger as rotas, colocando na descrição o exemplo padrão de retorno, dito como contrato da API, do modelo do dado no banco ou algo correspondente
- [ ] Criar uma nova rota da documentação no Swagger focada na v2 somente
- [ ] Escrever no router, as rotas com um prefixo `api/v2/`
- [ ] Criar as atividades específicas para cada rota para um melhor gerenciamento
